name: Create image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup git config
        run: |
          git config user.name "EnoobongEnoh25"
          git config user.email "enoobongenoh25@gmail.com"

      - name: Dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push new version
        run: git push

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag enoobongenoh25/eenoh_frontend:latest
#replace victoriamartinsahagun with your DockerHub username
#replace vueapp with the image name

      - name: Push to Docker Hub
        run: docker push enoobongenoh25/eenoh_frontend:latest
#replace victoriamartinsahagun with your DockerHub username
#replace vueapp with the image name